# Generated by Django 6.1.1 on 2026-09-11 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Event', 'Event'), ('Workshop', 'Workshop'), ('Hackathon', 'Hackathon'), ('Club Activity', 'Club Activity')], max_length=50)),
                ('organizer_name', models.CharField(max_length=100)),
                ('max_participants', models.PositiveIntegerField(default=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('is_past', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='clubs.club')),
                ('registered_users', models.ManyToManyField(blank=True, related_name='registered_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['date', 'time'],
            },
        ),
    ]
