# Generated by Django 6.1.1 on 2026-09-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_clubadminrequest_alter_club_options_club_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='club',
            name='instagram_handle',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
